### ISSUE TITLE
can't find zql jar

### ISSUE THREAD

**Issue by sherifyounis** [frmichel/morph-xr2rml#7]
zql:zql:jar:0.1 from http://nexus.i3s.unice.fr/content/repositories/i3s-public/

**Comment by sherifyounis** [comment]
[ERROR] Failed to execute goal on project morph-core: Could not resolve dependencies for project fr.unice.i3s:morph-core:jar:1.3.1: Failed to collect dependencies at zql:zql:jar:0.1: Failed to read artifact descriptor for zql:zql:jar:0.1: Could not transfer artifact zql:zql:pom:0.1 from/to codelds (https://code.lds.org/nexus/content/groups/main-repo): Transfer failed for https://code.lds.org/nexus/content/groups/main-repo/zql/zql/0.1/zql-0.1.pom: Unknown host code.ldschurch.o

**Comment by frmichel** [comment]
I had not noticed that but indeed our Nexus server is down.
Until we set it back on line, I've copied the jar here: https://www.dropbox.com/s/nk7pr5bifoil24u/zql.zip?dl=0
Simply unzip this to your .m2 repository.

Please met me know when this is done.

**Comment by frmichel** [comment]
Hi, our Nexus service is restarted.
